production:
  base_url: 'https://worldcat.org/bib/data'
  wskey_url: 'https://authn.sd00.worldcat.org/oauth2'
  institutions:
    128807: 
      symbol: OCPSB
      name: "OCLC WorldShare Platform Sandbox Institution"
